// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZU8T1QBauAOwv2Hn9r-d_Hfc7Okv5DI',
    appId: '1:306132599412:android:3a11b26921c511f6a58721',
    messagingSenderId: '306132599412',
    projectId: 'we-chat-5b957',
    storageBucket: 'we-chat-5b957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPI1yTPTW24qewsb0RmqnVHuAwC8sapk',
    appId: '1:306132599412:ios:a98a1d49997cee07a58721',
    messagingSenderId: '306132599412',
    projectId: 'we-chat-5b957',
    storageBucket: 'we-chat-5b957.appspot.com',
    androidClientId: '306132599412-mdgu73vmr8tgr8lfqhggin5fbv50a0b0.apps.googleusercontent.com',
    iosClientId: '306132599412-402vmn49k660icivdtok7l9not9kdprc.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
